#!/bin/csh

if ( $#argv == 0 ) then
  echo "Imports VMD plugin files from external source tree into NAMD tree."
  echo "usage: $0 <plugins tree>"
  exit -1
endif

set dest=$0
set dest=$dest:h
if ( $dest == $0 ) set dest="."

set base=$1

echo Importing from $base to $dest

foreach file ( molfile_plugin.h vmdplugin.h )
  set dir=include
  set f=$base/$dir/$file
  echo $f
  \cp -f $f $dest/$dir
end

foreach file ( dcdplugin.c endianswap.h fastio.h )
  set dir=molfile_plugin/src
  set f=$base/$dir/$file
  echo $f
  \cp -f $f $dest/$dir
end

