# 
# Makefile to build dpmta_test and dpmta_slave on a serial workstation
#
# w. t. rankin
#
# Copyright (c) 1997 Duke University
# All rights reserved
#
# this makefile is set up to compile for the cray t3d (and c90 front end)
# for compilation on generic workstation networks should use the default
# makefile
#
# RCS Info: $Id: Makefile.serial,v 1.1 1997/09/05 19:41:48 jim Exp $
#
# Revision History:
# $Log: Makefile.serial,v $
# Revision 1.1  1997/09/05 19:41:48  jim
# Original distribution.
#
# Revision 2.9  1997/05/13  17:53:19  wrankin
# use basic types defined in mpe.h instead of redeclaring them
#
# Revision 2.8  1997/05/12  17:59:02  wrankin
# updated compiler declarations
#
# Revision 2.7  1997/05/07  21:27:42  chumphre
# cubectr changed to cellctr and other minor changes related to the interface
#
# Revision 2.6  1997/05/07  19:04:17  chumphre
# *** empty log message ***
#
# Revision 2.5  1997/03/26  20:20:39  wrankin
# fixed a couple of library definitions for dpmta_direct and dpmta_error
#
# Revision 2.4  1997/03/18  21:24:22  wrankin
# fixed error computation code
#
# Revision 2.3  1997/03/07  00:46:11  wrankin
# converted dpmta_direct to work serial without pvm
#
# Revision 2.2  1997/02/26  20:43:24  wrankin
# updated timing measurements and placed routines in single module
#
# Revision 2.1  1997/02/26  16:54:25  wrankin
# added support for serial non-pvm compilation of DPMTA
#
#
################################################################

MAKE   = make
SHELL  = /bin/sh
CC     = cc
AR     = ar


# library flags - set the flags to point to the directories
#   containing the MPOLE libraries and include files.

LDIR =  -L. -L../mpole
IDIR =  -I../mpole/

################################################################
#
#  nothing below this line should need to be modified
#
################################################################

CFLAGS = -O3 -DSERIAL $(DFLAGS) $(IDIR)
LDLIBS= -lspmta -lmpole -lm $(OSLIBS)
LDFLAGS = $(LDIR)


SSRC  =	dpmta_serial.c \
	dpmta_slvmkcell.c dpmta_slvmcalc.c dpmta_slvpcalc.c \
        dpmta_slvmisc.c dpmta_slvclean.c dpmta_slvstart.c \
	dpmta_slvmkil.c dpmta_slvmkhl.c \
	dpmta_slvcompute.c dpmta_slvmacro.c dpmta_slvscale.c \
	dpmta_timer.c
SOBJS =	$(SSRC:.c=.o)


TSRC1 = dpmta_test.c dpmta_test4.c
TSRC2 = dpmta_testdump.c
TOBJS = $(TSRC1:.c=.o) $(TSRC2:.c=.o)
TEXEC = $(TSRC1:.c=)


################################################################

default : all

all:
	$(MAKE) -f Makefile.serial libspmta.a CFLAGS="$(CFLAGS)" CC=$(CC)
	$(MAKE) -f Makefile.serial dpmta_test CFLAGS="$(CFLAGS)" \
		LDLIBS="$(LDLIBS)" LDFLAGS="$(LDFLAGS)" CC=$(CC)
	$(MAKE) -f Makefile.serial dpmta_test4 CFLAGS="$(CFLAGS)" \
		LDLIBS="$(LDLIBS)" LDFLAGS="$(LDFLAGS)" CC=$(CC)
	$(MAKE) -f Makefile.serial dpmta_direct CFLAGS="$(CFLAGS)" \
		LDLIBS="-lm" LDFLAGS="$(LDFLAGS)" CC=$(CC)
	$(MAKE) -f Makefile.serial dpmta_error CFLAGS="$(CFLAGS)" \
	        LDLIBS="-lm" LDFLAGS="$(LDFLAGS)" CC=$(CC)

libspmta.a : $(SOBJS)
	$(AR) r libspmta.a $(SOBJS)

dpmta_test : dpmta_test.o dpmta_testdump.o libspmta.a ../mpole/libmpole.a
	$(CC) -o dpmta_test $(CFLAGS) $(LDFLAGS) dpmta_test.o \
	   dpmta_testdump.o $(LDLIBS)

dpmta_test4 : dpmta_test4.o dpmta_testdump.o libspmta.a ../mpole/libmpole.a
	$(CC) -o dpmta_test4 $(CFLAGS) $(LDFLAGS) dpmta_test4.o \
	   dpmta_testdump.o $(LDLIBS)

dpmta_direct : dpmta_direct.o
	$(CC) -o dpmta_direct $(CFLAGS) $(LDFLAGS) dpmta_direct.o \
	   dpmta_testdump.o  $(LDLIBS)

dpmta_error : dpmta_error.o
	$(CC) -o dpmta_error $(CFLAGS) $(LDFLAGS) dpmta_error.o $(LDLIBS)


clean:
	rm -f dpmta_test dpma_test4 libspmta.a
	rm -f $(SOBJS) $(TOBJS) $(TEXEC)

install: all

#
#  include file dependencies
#

dpmta_test.c : dpmta.h

dpmta_test4.c : dpmta.h

dpmta_serial.c : dpmta.h dpmta_cell.h

dpmta_mastiter.c : dpmta_cell.h dpmta_pvm.h 

dpmta_slvmkcell.c : dpmta_cell.h dpmta_pvm.h dpmta_slave.h

dpmta_slvmcalc.c :  dpmta_cell.h dpmta_pvm.h dpmta_slave.h

dpmta_slvpcalc.c : dpmta_cell.h dpmta_pvm.h dpmta_slave.h

dpmta_slvmisc.c : dpmta_cell.h dpmta_pvm.h dpmta_slave.h

dpmta_slvcomm.c : dpmta_cell.h dpmta_pvm.h dpmta_slave.h

dpmta_slvclean.c : dpmta_cell.h dpmta_slave.h

dpmta_slvmkhl.c : dpmta_cell.h dpmta_slave.h dpmta_slvmkil.h

dpmta_slvmkil.c : dpmta_cell.h dpmta_slave.h 

dpmta_slvmkiil.c : dpmta_cell.h dpmta_pvm.h dpmta_slave.h

dpmta_slvcompute.c : dpmta_cell.h dpmta_slave.h

