# 
# Makefile to build dpmta_test and dpmta_slave on Cray T3D
#
# w. t. rankin
#
# Copyright (c) 1997 Duke University
# All rights reserved
#
# this makefile is set up to compile for the cray t3d (and c90 front end)
# for compilation on generic workstation networks should use the default
# makefile
#
# RCS Info: $Id: Makefile.converse,v 1.4 1997/12/17 15:22:28 milind Exp $
#
# Revision History:
# $Log: Makefile.converse,v $
# Revision 1.4  1997/12/17 15:22:28  milind
# Fixed a makefile bug to take care of PVM_ARCH.
#
# Revision 1.3  1997/09/29 23:58:33  jim
# Incorporated changes from version 2.6.1 of DPMTA.
#   - fixes for bad handling of empty/invalid multipoles when
#     using large processor sets.
#   - moved functions that provide data mapping to processors.  master
#     and slave routines now call the same function in dpmta_distmisc.c
# Also, switched pvmc.h back to pvm3.h.
#
# Revision 1.2  1997/09/28 10:24:07  milind
# Fixed Makefiles to include arch params from a single file.
#
# Revision 1.1  1997/09/12 22:56:28  jim
# Modifications to work with converse pvm.
#
# Revision 1.1  1997/09/05 19:41:47  jim
# Original distribution.
#
# Revision 2.11  1997/05/13  17:53:18  wrankin
# use basic types defined in mpe.h instead of redeclaring them
#
# Revision 2.10  1997/04/28  16:01:47  wrankin
# fix to timer code to make consistant with distributed impl.
# fit to handling of cell length to make consistant with distributed impl.
#
# Revision 2.9  1997/02/26  18:52:28  wrankin
# cleaned up handling of cell resizing
#
# Revision 2.8  1997/02/26  16:52:03  wrankin
# added copyright notice
#
# Revision 2.7  1997/01/29  20:24:18  wrankin
# changes to support compilation for Cray T3E
#
# Revision 2.6  1997/01/13  22:10:04  wrankin
# added supprt for dpmta_test5.c which does MIMD with PDB file input
#
# Revision 2.5  1996/11/01  02:26:42  wrankin
# modifications to support cray t3d compilation
# version update for 2.5 release
#
# Revision 2.4  1996/09/24  18:41:24  wrankin
# many changes for support of version 2.5
#  - non cubic cells
#  - non power-of-2 processors
#  - fixed the resize code
#  - new virial interface
#  - changes to macroscopic code (still not working)
#  - code cleanup
#  - new test program that reads PDB file
#  - update code for T3D support
#
# Revision 2.3  1995/07/26  01:52:56  wrankin
# updated Makefiles
# slight performance improvement for direct calculations
# clean up test code example
# fixed t3dlib for new multipole code
#
# Revision 2.2  1995/07/17 01:13:34  wrankin
# updates to support SGI Power Challenge (IRIX 6.0.1)
# cleanup of Makefile
# initial work on T3D port (not yet supported in this release)
#
# Revision 2.1  1995/06/13  04:25:58  wrankin
# No updates.
# Sources placed under CVS.
#
# Revision 1.3  1995/05/15  19:33:57  wrankin
# removded dependancy declaration for dpmta_mastilist.c
# added dependancy declaration for dpmta_mastmkil.c
#
# Revision 1.2  1995/04/24  04:33:11  wrankin
# updated to actually work on the T3D at NCSC
#
# Revision 1.1  1995/01/01  15:01:53  wrankin
# Initial revision
#
#
################################################################

include ../../Makearch

# tell the compiler where to locate the PVM include
# files
#

PVM_IDIR = ../../pvm3
IDIR = -I$(PVM_IDIR) -I../mpole/ -I$(CHARM)/include

#
# library flags - set the flags to point to the directories
#   containing the PVM and DPMTA libraries.  the cray t3d is
#   a special case since the libraries are different for the
#   master and slave processes, and also not located in the
#   standard place.
#

PVM_LDIR = ../../pvm3/lib
LDIR =  -L. -L../mpole -L$(PVM_LDIR)


################################################################
#
#  nothing below this line should need to be modified
#
################################################################

CFLAGS = -D$(PVM_ARCH) -DEMBEDDED $(DFLAGS) $(IDIR)
LDLIBS= -ldpmta2 -lmpole -lpvm3 -lm $(OSLIBS)
LDFLAGS = $(LDIR)


SSRC  =	dpmta_t3dlib.c dpmta_mastiter.c dpmta_mastinit.c \
	dpmta_slvmkcell.c dpmta_slvmcalc.c dpmta_slvpcalc.c \
        dpmta_slvcomm.c  dpmta_slvclean.c dpmta_slvstart.c \
	dpmta_slvmkiil.c  dpmta_slvmkil.c dpmta_slvmkhl.c \
	dpmta_slvcompute.c dpmta_slvmacro.c dpmta_slvscale.c \
	dpmta_timer.c \
	dpmta_distmisc.c
SOBJS =	$(SSRC:.c=.o)


TSRC1 = dpmta_test3.c dpmta_direct.c dpmta_test5.c
TSRC2 = dpmta_testdump.c
TOBJS = $(TSRC1:.c=.o) $(TSRC2:.c=.o)
TEXEC = $(TSRC1:.c=)


################################################################

default : all

all:
	$(MAKE) -f Makefile.cray libdpmta2.a CFLAGS="$(CFLAGS)"
	$(MAKE) -f Makefile.cray dpmta_test3 CFLAGS="$(CFLAGS)" \
		LDLIBS="$(LDLIBS)" LDFLAGS="$(LDFLAGS)"
	$(MAKE) -f Makefile.cray dpmta_test5 CFLAGS="$(CFLAGS)" \
		LDLIBS="$(LDLIBS)" LDFLAGS="$(LDFLAGS)"
	$(MAKE) -f Makefile.cray dpmta_direct CFLAGS="$(CFLAGS)" \
		LDLIBS="$(LDLIBS)" LDFLAGS="$(LDFLAGS)"

libdpmta2.a : $(SOBJS)
	$(AR) r libdpmta2.a $(SOBJS)

dpmta_test2 : dpmta_test2.o libdpmta2.a
	$(CC) -o dpmta_test2 $(CFLAGS) $(LDFLAGS) dpmta_test2.o $(LDLIBS)

dpmta_test2b : dpmta_test2b.o libdpmta2.a
	$(CC) -o dpmta_test2b $(CFLAGS) $(LDFLAGS) dpmta_test2b.o $(LDLIBS)

dpmta_test3 : dpmta_test3.o dpmta_testdump.o libdpmta2.a
	$(CC) -o dpmta_test3 $(CFLAGS) $(LDFLAGS) dpmta_test3.o \
	dpmta_testdump.o $(LDLIBS)

dpmta_test5 : dpmta_test5.o dpmta_testdump.o libdpmta2.a
	$(CC) -o dpmta_test5 $(CFLAGS) $(LDFLAGS) dpmta_test5.o \
	dpmta_testdump.o $(LDLIBS)

dpmta_direct : dpmta_direct.o
	$(CC) -o dpmta_direct $(CFLAGS) $(LDFLAGS) dpmta_direct.o $(LDLIBS)

clean:
	rm -f dpmta_test3 libdpmta2.a $(SOBJS) $(TOBJS) $(TEXEC)

install: all
	cp $(TEXEC) $(PVM_HOME)/bin/$(PVM_ARCH)
#	cp libdpmta2.a $(PVM_HOME)/lib/$(PVM_ARCH)

#
#  include file dependencies
#

dpmta_test3.c : dpmta.h

dpmta_test5.c : dpmta.h

dpmta_t3dlib.c : dpmta.h dpmta_cell.h dpmta_pvm.h

dpmta_mastiter.c : dpmta_cell.h dpmta_pvm.h 

dpmta_slvmkcell.c : dpmta_cell.h dpmta_pvm.h dpmta_slave.h

dpmta_slvmcalc.c :  dpmta_cell.h dpmta_pvm.h dpmta_slave.h

dpmta_slvpcalc.c : dpmta_cell.h dpmta_pvm.h dpmta_slave.h

dpmta_slvmisc.c : dpmta_cell.h dpmta_pvm.h dpmta_slave.h

dpmta_slvcomm.c : dpmta_cell.h dpmta_pvm.h dpmta_slave.h

dpmta_slvclean.c : dpmta_cell.h dpmta_slave.h

dpmta_slvmkhl.c : dpmta_cell.h dpmta_slave.h dpmta_slvmkil.h

dpmta_slvmkil.c : dpmta_cell.h dpmta_slave.h 

dpmta_slvmkiil.c : dpmta_cell.h dpmta_pvm.h dpmta_slave.h

dpmta_slvcompute.c : dpmta_cell.h dpmta_slave.h

