
TCLDIR = $(HOME)/tcl-win64
TCLINCL = -I$(TCLDIR)/include
TCLLIB = -L$(TCLDIR)/lib -ltcl85
TCLDLL = tcl85.dll
TCLFLAGS = -DNAMD_TCL
TCL = $(TCLINCL) $(TCLFLAGS)

$(TCLSENTINEL)$(TCLDLL):
	$(COPY) $(TCLDIR)/bin/$(TCLDLL) $(TCLDLL)
TCLSENTINEL = not_$(TCLSENTIEL)

