#include "charm++.h"
#include "CollectionMgr.decl.h"
#include "CollectionMgr.h"
#include "CollectionMaster.decl.h"
#include "CollectionMaster.h"
#include "Node.h"
#include "Molecule.h"
#include "SimParameters.h"

//#define DEBUGM
#include "Debug.h"

CollectionMgr::CollectionMgr(SlaveInitMsg *msg) : master(msg->master)
{
  delete msg;
  if (CpvAccess(CollectionMgr_instance) == 0) {
    CpvAccess(CollectionMgr_instance) = this;
  } else {
    DebugM(1, "CollectionMgr::CollectionMgr() - another instance of CollectionMgr exists!\n");
  }
}


CollectionMgr::~CollectionMgr(void)
{
}


void CollectionMgr::submitPositions(int seq, AtomIDList &i, PositionList &d,
				Lattice l, TransformList &t, int prec)
{
  int wrapWater = Node::Object()->simParameters->wrapWater;
  Molecule *mol = Node::Object()->molecule;
  PositionList d2(d.size());
  PositionList::iterator d_i,d_e,d2_i;
  AtomIDList::iterator a_i = i.begin();
  TransformList::iterator t_i = t.begin();
  d_i = d.begin();  d_e = d.end();  d2_i = d2.begin();
  for ( ; d_i != d_e ; ++d_i, ++d2_i, ++a_i, ++t_i ) {
    if ( wrapWater && mol->is_water(*a_i) ) {
      *d2_i = *d_i;
    } else {
      *d2_i = l.reverse_transform(*d_i,*t_i);
    }
  }
  CollectVectorInstance *c;
  if ( ( c = positions.submitData(seq,i,d2,prec) ) )
  {
    CollectVectorMsg * msg = new CollectVectorMsg;
    msg->seq = c->seq;
    msg->aid = c->aid;
    msg->data = c->data;
    msg->fdata = c->fdata;
    CProxy_CollectionMaster cm(master);
    cm.receivePositions(msg);
    delete c;
  }
}


void CollectionMgr::submitVelocities(int seq, AtomIDList &i, VelocityList &d)
{
  CollectVectorInstance *c;
  if ( ( c = velocities.submitData(seq,i,d) ) )
  {
    CollectVectorMsg * msg = new CollectVectorMsg;
    msg->seq = c->seq;
    msg->aid = c->aid;
    msg->data = c->data;
    CProxy_CollectionMaster cm(master);
    cm.receiveVelocities(msg);
    delete c;
  }
}


void CollectionMgr::submitForces(int seq, AtomIDList &i, ForceList &d)
{
  CollectVectorInstance *c;
  if ( ( c = forces.submitData(seq,i,d) ) )
  {
    CollectVectorMsg * msg = new CollectVectorMsg;
    msg->seq = c->seq;
    msg->aid = c->aid;
    msg->data = c->data;
    CProxy_CollectionMaster cm(master);
    cm.receiveForces(msg);
    delete c;
  }
}


#include "CollectionMgr.def.h"

/***************************************************************************
 * RCS INFORMATION:
 *
 *	$RCSfile $
 *	$Author $	$Locker:  $		$State: Exp $
 *	$Revision: 1.1015 $	$Date: 1999/09/12 19:33:15 $
 *
 ***************************************************************************
 * REVISION HISTORY:
 *
 * $Log: CollectionMgr.C,v $
 * Revision 1.1015  1999/09/12 19:33:15  jim
 * Collections now use floats when possible.
 *
 * Revision 1.1014  1999/05/11 23:56:15  brunner
 * Changes for new charm version
 *
 * Revision 1.1013  1999/01/18 21:53:56  brunner
 * Changes to deal with recent Charm++ changes.  More extensive changes
 * may be needed soon, but this works for now.
 *
 * Revision 1.1012  1998/10/24 19:57:19  jim
 * Eliminated warnings generated by g++ -Wall.
 *
 * Revision 1.1011  1998/08/17 23:34:30  jim
 * Added options for Langevin piston and wrapWater.
 *
 * Revision 1.1010  1998/08/11 16:30:25  jim
 * Modified output from periodic boundary simulations to return atoms to
 * internally consistent coordinates.  We store the transformations which
 * were performed and undo them at the end.  It might be better to do this
 * by always keeping the original coordinates and only doing the transform
 * for the nonbonded terms but this works for now.
 *
 * Revision 1.1009  1998/02/10 23:30:26  milind
 * Fixed to reflect the current changes to Charm++ translator.
 *
 * Revision 1.1008  1997/11/07 20:17:35  milind
 * Made NAMD to run on shared memory machines.
 *
 * Revision 1.1007  1997/09/28 10:19:02  milind
 * Fixed priorities, ReductionMgr etc.
 *
 * Revision 1.1006  1997/08/26 16:26:10  jim
 * Revamped prioritites for petter performance and easier changes.
 *
 * Revision 1.1005  1997/08/22 20:12:03  milind
 * Turned on Priorities.
 *
 * Revision 1.1004  1997/07/08 15:48:06  milind
 * Made namd2 to work with Origin2000: Again...
 *
 * Revision 1.1003  1997/04/08 07:08:07  ari
 * Modification for dynamic loadbalancing - moving computes
 * Still bug in new computes or usage of proxies/homepatches.
 * Works if ldbStrategy is none as before.
 *
 * Revision 1.1002  1997/04/06 22:44:56  ari
 * Add priorities to messages.  Mods to help proxies without computes.
 * Added quick enhancement to end of list insertion of ResizeArray(s)
 *
 * Revision 1.1001  1997/03/19 11:53:58  ari
 * Add Broadcast mechanism.
 * Fixed RCS Log entries on files that did not have Log entries.
 * Added some register variables to Molecule and ComputeNonbondedExcl.C
 *
 ***************************************************************************/
