/***************************************************************************/
/*         (C) Copyright 1996,1997 The Board of Trustees of the            */
/*                          University of Illinois                         */
/*                           All Rights Reserved                           */
/***************************************************************************/
/***************************************************************************
 * DESCRIPTION:  Messages needed for ComputePme operation.
 *		
 ***************************************************************************/

#include "ComputePmeMsgs.h"

//#define DEBUGM
#define MIN_DEBUG_LEVEL 3
#include "Debug.h"

#include "ComputeMgr.decl.h"

#include "PmeBase.h"

// DATA MESSAGE

ComputePmeDataMsg::ComputePmeDataMsg(void) { 
  numParticles = 0;
  particles = 0;
}

ComputePmeDataMsg::~ComputePmeDataMsg(void) { 
  delete [] particles;
}

void * ComputePmeDataMsg::pack (ComputePmeDataMsg *msg) {
  int length = 2 * sizeof(int) + msg->numParticles * sizeof(PmeParticle);

  char *buffer;
  char *b = buffer = (char*)CkAllocBuffer(msg,length);

  memcpy(b, &(msg->node), sizeof(int)); b += sizeof(int);
  memcpy(b, &(msg->numParticles), sizeof(int)); b += sizeof(int);
  memcpy(b, msg->particles, msg->numParticles*sizeof(PmeParticle));
  b += msg->numParticles*sizeof(PmeParticle);
  delete msg;
  return buffer;
}

ComputePmeDataMsg* ComputePmeDataMsg::unpack (void *ptr) {
  void *_ptr = CkAllocBuffer(ptr, sizeof(ComputePmeDataMsg));
  ComputePmeDataMsg* m = new (_ptr) ComputePmeDataMsg;
  char *b = (char*)ptr;

  memcpy(&(m->node), b, sizeof(int)); b += sizeof(int);
  memcpy(&(m->numParticles), b, sizeof(int)); b += sizeof(int);
  m->particles = new PmeParticle[m->numParticles];
  memcpy(m->particles, b, m->numParticles*sizeof(PmeParticle));
  CkFreeMsg(ptr);
  return m;
}


// RESULTS MESSAGE

ComputePmeResultsMsg::ComputePmeResultsMsg(void) { 
  numParticles = 0;
  forces = 0;
}

ComputePmeResultsMsg::~ComputePmeResultsMsg(void) { 
  delete [] forces;
}

void * ComputePmeResultsMsg::pack (ComputePmeResultsMsg *msg) {
  int length = 2 * sizeof(int) + msg->numParticles * sizeof(PmeParticle);

  char *buffer;
  char *b = buffer = (char*)CkAllocBuffer(msg,length);

  memcpy(b, &(msg->node), sizeof(int)); b += sizeof(int);
  memcpy(b, &(msg->numParticles), sizeof(int)); b += sizeof(int);
  memcpy(b, msg->forces, msg->numParticles*sizeof(PmeVector));
  delete msg;
  return buffer;
}

ComputePmeResultsMsg* ComputePmeResultsMsg::unpack (void *ptr) {
  void *_ptr = CkAllocBuffer(ptr, sizeof(ComputePmeResultsMsg));
  ComputePmeResultsMsg*m = new (_ptr) ComputePmeResultsMsg;
  char *b = (char*)ptr;

  memcpy(&(m->node), b, sizeof(int)); b += sizeof(int);
  memcpy(&(m->numParticles), b, sizeof(int)); b += sizeof(int);
  m->forces = new PmeVector[m->numParticles];
  memcpy(m->forces, b, m->numParticles*sizeof(PmeVector));
  CkFreeMsg(ptr);
  return m;
}



/***************************************************************************
 * RCS INFORMATION:
 *
 *	$RCSfile: ComputePmeMsgs.C,v $
 *	$Author: jim $	$Locker:  $		$State: Exp $
 *	$Revision: 1.1 $	$Date: 1999/06/08 14:52:07 $
 *
 * REVISION HISTORY:
 *
 * $Log: ComputePmeMsgs.C,v $
 * Revision 1.1  1999/06/08 14:52:07  jim
 * Incorporated Justin's faster PME code along side DPME.
 *
 * Revision 1.3  1999/05/11 23:56:18  brunner
 * Changes for new charm version
 *
 * Revision 1.2  1998/10/24 19:57:21  jim
 * Eliminated warnings generated by g++ -Wall.
 *
 * Revision 1.1  1998/04/10 04:15:58  jim
 * Finished incorporating DPME.
 *
 *
 ***************************************************************************/
