/***************************************************************************/
/*         (C) Copyright 1996,1997 The Board of Trustees of the            */
/*                          University of Illinois                         */
/*                           All Rights Reserved                           */
/***************************************************************************/
/***************************************************************************
 * DESCRIPTION:  Messages needed for ComputeDPME operation.
 *		
 ***************************************************************************/

#include "ComputeDPMEMsgs.h"

//#define DEBUGM
#define MIN_DEBUG_LEVEL 3
#include "Debug.h"

#include "ComputeMgr.decl.h"

#ifdef DPME
#include "dpme2.h"
#else
#define Pme2Particle char;
#define PmeVector char;
#endif

// DATA MESSAGE

ComputeDPMEDataMsg::ComputeDPMEDataMsg(void) { 
  numParticles = 0;
  particles = 0;
}

ComputeDPMEDataMsg::~ComputeDPMEDataMsg(void) { 
  delete [] particles;
}

void * ComputeDPMEDataMsg::pack (ComputeDPMEDataMsg *msg) {
  int length = 2 * sizeof(int) + msg->numParticles * sizeof(Pme2Particle);

  char *buffer;
  char *b = buffer = (char*)CkAllocBuffer(msg,length);

  memcpy(b, &(msg->node), sizeof(int)); b += sizeof(int);
  memcpy(b, &(msg->numParticles), sizeof(int)); b += sizeof(int);
  memcpy(b, msg->particles, msg->numParticles*sizeof(Pme2Particle));
  b += msg->numParticles*sizeof(Pme2Particle);
  delete msg;
  return buffer;
}

ComputeDPMEDataMsg* ComputeDPMEDataMsg::unpack (void *ptr) {
  void *_ptr = CkAllocBuffer(ptr, sizeof(ComputeDPMEDataMsg));
  ComputeDPMEDataMsg* m = new (_ptr) ComputeDPMEDataMsg;
  char *b = (char*)ptr;

  memcpy(&(m->node), b, sizeof(int)); b += sizeof(int);
  memcpy(&(m->numParticles), b, sizeof(int)); b += sizeof(int);
  m->particles = new Pme2Particle[m->numParticles];
  memcpy(m->particles, b, m->numParticles*sizeof(Pme2Particle));
  CkFreeMsg(ptr);
  return m;
}


// RESULTS MESSAGE

ComputeDPMEResultsMsg::ComputeDPMEResultsMsg(void) { 
  numParticles = 0;
  forces = 0;
}

ComputeDPMEResultsMsg::~ComputeDPMEResultsMsg(void) { 
  delete [] forces;
}

void * ComputeDPMEResultsMsg::pack (ComputeDPMEResultsMsg *msg) {
  int length = 2 * sizeof(int) + msg->numParticles * sizeof(Pme2Particle);

  char *buffer;
  char *b = buffer = (char*)CkAllocBuffer(msg,length);

  memcpy(b, &(msg->node), sizeof(int)); b += sizeof(int);
  memcpy(b, &(msg->numParticles), sizeof(int)); b += sizeof(int);
  memcpy(b, msg->forces, msg->numParticles*sizeof(PmeVector));
  delete msg;
  return buffer;
}

ComputeDPMEResultsMsg* ComputeDPMEResultsMsg::unpack (void *ptr) {
  void *_ptr = CkAllocBuffer(ptr, sizeof(ComputeDPMEResultsMsg));
  ComputeDPMEResultsMsg*m = new (_ptr) ComputeDPMEResultsMsg;
  char *b = (char*)ptr;

  memcpy(&(m->node), b, sizeof(int)); b += sizeof(int);
  memcpy(&(m->numParticles), b, sizeof(int)); b += sizeof(int);
  m->forces = new PmeVector[m->numParticles];
  memcpy(m->forces, b, m->numParticles*sizeof(PmeVector));
  CkFreeMsg(ptr);
  return m;
}



/***************************************************************************
 * RCS INFORMATION:
 *
 *	$RCSfile: ComputeDPMEMsgs.C,v $
 *	$Author: brunner $	$Locker:  $		$State: Exp $
 *	$Revision: 1.3 $	$Date: 1999/05/11 23:56:18 $
 *
 * REVISION HISTORY:
 *
 * $Log: ComputeDPMEMsgs.C,v $
 * Revision 1.3  1999/05/11 23:56:18  brunner
 * Changes for new charm version
 *
 * Revision 1.2  1998/10/24 19:57:21  jim
 * Eliminated warnings generated by g++ -Wall.
 *
 * Revision 1.1  1998/04/10 04:15:58  jim
 * Finished incorporating DPME.
 *
 *
 ***************************************************************************/
