/***************************************************************************/
/*         (C) Copyright 1996,1997 The Board of Trustees of the            */
/*                          University of Illinois                         */
/*                           All Rights Reserved                           */
/***************************************************************************/
/***************************************************************************
 * DESCRIPTION:  Messages needed for ComputeGlobal operation.
 *		
 ***************************************************************************/

#include "ComputeGlobalMsgs.h"
#include "packmsg.h"

//#define DEBUGM
#define MIN_DEBUG_LEVEL 3
#include "Debug.h"

#include "ComputeMgr.decl.h"


// CONFIG MESSAGE

ComputeGlobalConfigMsg::ComputeGlobalConfigMsg(void) { 
}

ComputeGlobalConfigMsg::~ComputeGlobalConfigMsg(void) { 
}

PACK_MSG(ComputeGlobalConfigMsg,
  PACK_RESIZE(aid);
  PACK_RESIZE(gdef);
)


// DATA MESSAGE

ComputeGlobalDataMsg::ComputeGlobalDataMsg(void) { 
}

ComputeGlobalDataMsg::~ComputeGlobalDataMsg(void) { 
}

PACK_MSG(ComputeGlobalDataMsg,
  PACK_RESIZE(aid);
  PACK_RESIZE(p);
  PACK_RESIZE(gcom);
)


// RESULTS MESSAGE

ComputeGlobalResultsMsg::ComputeGlobalResultsMsg(void) { 
  reconfig = 0;
}

ComputeGlobalResultsMsg::~ComputeGlobalResultsMsg(void) { 
}

PACK_MSG(ComputeGlobalResultsMsg,
  PACK_RESIZE(aid);
  PACK_RESIZE(f);
  PACK_RESIZE(gforce);
  PACK(reconfig);
  if ( packmsg_msg->reconfig ) {
    PACK_RESIZE(newaid);
    PACK_RESIZE(newgdef);
  }
)


/***************************************************************************
 * RCS INFORMATION:
 *
 *	$RCSfile: ComputeGlobalMsgs.C,v $
 *	$Author: jim $	$Locker:  $		$State: Exp $
 *	$Revision: 1.5 $	$Date: 1999/09/24 17:15:08 $
 *
 * REVISION HISTORY:
 *
 * $Log: ComputeGlobalMsgs.C,v $
 * Revision 1.5  1999/09/24 17:15:08  jim
 * Added packmsg.h with macros to simplify packing.
 *
 * Revision 1.4  1999/05/11 23:56:22  brunner
 * Changes for new charm version
 *
 * Revision 1.3  1998/10/24 19:57:24  jim
 * Eliminated warnings generated by g++ -Wall.
 *
 * Revision 1.2  1998/02/16 00:24:38  jim
 * Added atom group centers of mass to Tcl interface.
 *
 * Revision 1.1  1997/12/19 23:48:47  jim
 * Added Tcl interface for calculating forces.
 *
 *
 ***************************************************************************/
