/***************************************************************************/
/*         (C) Copyright 1996,1997 The Board of Trustees of the            */
/*                          University of Illinois                         */
/*                           All Rights Reserved                           */
/***************************************************************************/
/***************************************************************************
 * DESCRIPTION:  Messages needed for ComputeDPME operation.
 *		
 ***************************************************************************/

#include "ComputeDPMEMsgs.h"
#include "packmsg.h"

//#define DEBUGM
#define MIN_DEBUG_LEVEL 3
#include "Debug.h"

// DATA MESSAGE

ComputeDPMEDataMsg::ComputeDPMEDataMsg(void) { 
  numParticles = 0;
  particles = 0;
}

ComputeDPMEDataMsg::~ComputeDPMEDataMsg(void) { 
  delete [] particles;
}

PACK_MSG(ComputeDPMEDataMsg,
  PACK(node);
  PACK_AND_NEW_ARRAY(particles,numParticles);
)


// RESULTS MESSAGE

ComputeDPMEResultsMsg::ComputeDPMEResultsMsg(void) { 
  numParticles = 0;
  forces = 0;
}

ComputeDPMEResultsMsg::~ComputeDPMEResultsMsg(void) { 
  delete [] forces;
}

PACK_MSG(ComputeDPMEResultsMsg,
  PACK(node);
  PACK_AND_NEW_ARRAY(forces,numParticles);
)


/***************************************************************************
 * RCS INFORMATION:
 *
 *	$RCSfile: ComputeDPMEMsgs.C,v $
 *	$Author: jim $	$Locker:  $		$State: Exp $
 *	$Revision: 1.5 $	$Date: 1999/09/24 17:15:08 $
 *
 * REVISION HISTORY:
 *
 * $Log: ComputeDPMEMsgs.C,v $
 * Revision 1.5  1999/09/24 17:15:08  jim
 * Added packmsg.h with macros to simplify packing.
 *
 * Revision 1.4  1999/09/08 16:05:44  jim
 * Added internal PUB3DFFT package.
 *
 * Revision 1.3  1999/05/11 23:56:18  brunner
 * Changes for new charm version
 *
 * Revision 1.2  1998/10/24 19:57:21  jim
 * Eliminated warnings generated by g++ -Wall.
 *
 * Revision 1.1  1998/04/10 04:15:58  jim
 * Finished incorporating DPME.
 *
 *
 ***************************************************************************/
