/***************************************************************************/
/*         (C) Copyright 1996,1997 The Board of Trustees of the            */
/*                          University of Illinois                         */
/*                           All Rights Reserved                           */
/***************************************************************************/
/***************************************************************************
 * DESCRIPTION:  Messages needed for ComputePme operation.
 *		
 ***************************************************************************/

#include "ComputePmeMsgs.h"
#include "packmsg.h"

//#define DEBUGM
#define MIN_DEBUG_LEVEL 3
#include "Debug.h"

#include "ComputeMgr.decl.h"

#include "PmeBase.h"


// DATA MESSAGE

ComputePmeDataMsg::ComputePmeDataMsg(void) { 
  numParticles = 0;
  particles = 0;
}

ComputePmeDataMsg::~ComputePmeDataMsg(void) { 
  delete [] particles;
}

PACK_MSG(ComputePmeDataMsg,
  PACK(node);
  PACK_AND_NEW_ARRAY(particles,numParticles);
)


// RESULTS MESSAGE

ComputePmeResultsMsg::ComputePmeResultsMsg(void) { 
  numParticles = 0;
  forces = 0;
}

ComputePmeResultsMsg::~ComputePmeResultsMsg(void) { 
  delete [] forces;
}

PACK_MSG(ComputePmeResultsMsg,
  PACK(node);
  PACK_AND_NEW_ARRAY(forces,numParticles);
)


/***************************************************************************
 * RCS INFORMATION:
 *
 *	$RCSfile: ComputePmeMsgs.C,v $
 *	$Author: jim $	$Locker:  $		$State: Exp $
 *	$Revision: 1.3 $	$Date: 1999/09/24 17:15:09 $
 *
 * REVISION HISTORY:
 *
 * $Log: ComputePmeMsgs.C,v $
 * Revision 1.3  1999/09/24 17:15:09  jim
 * Added packmsg.h with macros to simplify packing.
 *
 * Revision 1.2  1999/09/03 20:46:11  jim
 * Support for non-orthogonal periodic boundary conditions.
 *
 * Revision 1.1  1999/06/08 14:52:07  jim
 * Incorporated Justin's faster PME code along side DPME.
 *
 * Revision 1.3  1999/05/11 23:56:18  brunner
 * Changes for new charm version
 *
 * Revision 1.2  1998/10/24 19:57:21  jim
 * Eliminated warnings generated by g++ -Wall.
 *
 * Revision 1.1  1998/04/10 04:15:58  jim
 * Finished incorporating DPME.
 *
 *
 ***************************************************************************/
