//-*-c++-*-
/***************************************************************************/
/*                                                                         */
/*              (C) Copyright 1996 The Board of Trustees of the            */
/*                          University of Illinois                         */
/*                           All Rights Reserved                           */
/*									   */
/***************************************************************************/

/***************************************************************************
 * DESCRIPTION:
 *
 ***************************************************************************/

#ifndef CONTROLLER_H
#define CONTROLLER_H

#include "converse.h"
#include "Node.h"
#include "common.h"
#include <fstream.h>

class ControllerBroadcasts;
class NamdState;
class SimParameters;
class RequireReduction;
class CollectionMaster;

class Controller
{
public:
    Controller(NamdState *s);
    virtual ~Controller(void);
    void run(void);             // spawn thread, etc.
    void awaken(void) { CthAwaken(thread); };

protected:
    virtual void algorithm(void);	// subclasses redefine this method

    void receivePressure(int);
      Vector pressure_normal;
      Vector pressure_nbond;
      Vector pressure_slow;
      Vector groupPressure_normal;
      Vector groupPressure_nbond;
      Vector groupPressure_slow;
      Vector controlPressure_normal;
      Vector controlPressure_nbond;
      Vector controlPressure_slow;
      int nbondFreq;
      int slowFreq;
    void printEnergies(int);
      int computeChecksum;
      int numDegFreedom;
      BigReal kineticEnergy;
      BigReal temperature;
      Vector pressure;
      Vector groupPressure;
      int controlNumDegFreedom;
      Vector controlPressure;
    void enqueueCollections(int);
    void rescaleVelocities(int);
      BigReal rescaleVelocities_sumTemps;
      int rescaleVelocities_numTemps;
    void reassignVelocities(int);
    void tcoupleVelocities(int);
    void berendsenPressure(int);
    void langevinPiston1(int);
    void langevinPiston2(int);
      Vector langevinPiston_strainRate;

    // void suspend(void) { CthSuspend(); };
    void terminate(void);

    SimParameters *const simParams;	// for convenience
    NamdState *const state;		// access data in state
    RequireReduction *reduction;
    CollectionMaster *const collection;
    ControllerBroadcasts * broadcast;
    ofstream xstFile;

private:
    CthThread thread;
    static void threadRun(Controller*);

    double startCTime;
    double startWTime;
    double startBenchTime;

};

#endif // CONTROLLER_H


/***************************************************************************
 * RCS INFORMATION:
 *
 *	$RCSfile $
 *	$Author $	$Locker:  $		$State: Exp $
 *	$Revision: 1.1024 $	$Date: 1999/07/08 21:26:43 $
 *
 ***************************************************************************
 * REVISION HISTORY:
 *
 * $Log: Controller.h,v $
 * Revision 1.1024  1999/07/08 21:26:43  jim
 * Eliminated compiler warnings.
 *
 * Revision 1.1023  1999/06/17 15:46:16  jim
 * Completely rewrote reduction system to eliminate need for sequence numbers.
 *
 * Revision 1.1022  1999/06/02 15:14:20  jim
 * Now waits for output files to be written before halting.
 *
 * Revision 1.1021  1999/05/11 23:56:30  brunner
 * Changes for new charm version
 *
 * Revision 1.1020  1999/01/06 22:50:31  jim
 * Anisotropic (flexible cell) Langevin Piston pressure control finished.
 *
 * Revision 1.1019  1998/12/07 03:54:30  jim
 * Constant pressure should work with multiple timestepping.
 * Still needs some testing.  Some debug code still enabled.
 *
 * Revision 1.1018  1998/11/29 22:00:58  jim
 * Added group-based pressure control to work with rigidBonds.
 * New option useGroupPressure, turned on automatically if needed.
 *
 * Revision 1.1017  1998/11/18 21:17:42  jim
 * Added checksum to make sure compute objects don't go missing.
 *
 * Revision 1.1016  1998/10/24 19:57:31  jim
 * Eliminated warnings generated by g++ -Wall.
 *
 * Revision 1.1015  1998/09/13 21:06:07  jim
 * Cleaned up output, defaults, etc.
 *
 * Revision 1.1014  1998/08/18 23:27:44  jim
 * First implementation of constant pressure.
 * Isotropic only, incompatible with multiple timestepping or SHAKE.
 *
 * Revision 1.1013  1998/08/04 04:07:21  jim
 * Added extended system file support and fixed lack of endi in SimParameters.
 *
 * Revision 1.1012  1998/08/03 15:31:19  jim
 * Added temperature reassignment.
 *
 * Revision 1.1011  1998/08/02 21:26:39  jim
 * Altered velocity rescaling to use averaged temperature.
 *
 * Revision 1.1010  1998/07/06 19:17:01  brunner
 * Changed path info in Makearch.T3E, changed patch partition equation,
 * and added timing prints to Controller
 *
 * Revision 1.1009  1998/03/31 04:55:44  jim
 * Added test mode, fixed errors in virial with full electrostatics.
 *
 * Revision 1.1008  1998/03/06 20:55:25  jim
 * Added temperature coupling.
 *
 * Revision 1.1007  1997/03/21 23:05:35  jim
 * Added Berendsen's pressure coupling method, won't work with MTS yet.
 *
 * Revision 1.1006  1997/03/19 22:44:23  jim
 * Revamped Controller/Sequencer, added velocity rescaling.
 *
 * Revision 1.1005  1997/03/19 11:54:14  ari
 * Add Broadcast mechanism.
 * Fixed RCS Log entries on files that did not have Log entries.
 * Added some register variables to Molecule and ComputeNonbondedExcl.C
 *
 ***************************************************************************/
