#include <stdio.h>
#include "common.h"
#include "Inform.h"
#include "string.h"

Inform::Inform(char *str)
{
   strncpy(name,str,15);
   name[15] = '\0';
}

Inform::~Inform(){}


Inform& Inform::operator<<(const char *str)
{

    sprintf(tmp_str,"%s",str);
    n = MAX_MSG_SIZE - strlen(buffer)-1; 
    strncat(buffer,tmp_str,n);
    return *this;
}

Inform& Inform::operator<<(char c)
{
    sprintf(tmp_str,"%c",c);
    n = MAX_MSG_SIZE - strlen(buffer)-1;
    strncat(buffer,tmp_str,n); 
    return *this;
}

Inform& Inform::operator<<(short i)
{
    sprintf(tmp_str,"%d",i);
    n = MAX_MSG_SIZE - strlen(buffer)-1;
    strncat(buffer,tmp_str,n);
    return *this;
}

Inform& Inform::operator<<(int i)
{
    sprintf(tmp_str,"%d",i);
    n = MAX_MSG_SIZE - strlen(buffer)-1;
    strncat(buffer,tmp_str,n); 
    return *this;
}


Inform& Inform::operator<<(unsigned int i)
{
    sprintf(tmp_str,"%d",i);
    n = MAX_MSG_SIZE - strlen(buffer)-1;
    strncat(buffer,tmp_str,n);
    return *this;
}

Inform& Inform::operator<<(long i)
{
    sprintf(tmp_str,"%ld",i);
    n = MAX_MSG_SIZE - strlen(buffer)-1;
    strncat(buffer,tmp_str,n);
    return *this;
}

Inform& Inform::operator<<(float f)
{
    sprintf(tmp_str,"%f",f);
    n = MAX_MSG_SIZE - strlen(buffer)-1;
    strncat(buffer,tmp_str,n);
    return *this;
}

Inform& Inform::operator<<(double f)
{
    sprintf(tmp_str,"%f",f);
    n = MAX_MSG_SIZE - strlen(buffer)-1;
    strncat(buffer,tmp_str,n);
    return *this;
}


void Inform::display_message()
{
    CPrintf("Node%d:%s>%s\n",0,name,buffer);
    buffer[0] = '\0';
}



Inform& sendmsg(Inform& inform)
{
    inform.display_message();
    return inform;
}



/***************************************************************************
 * RCS INFORMATION:
 *
 *	$RCSfile $
 *	$Author $	$Locker:  $		$State: Exp $
 *	$Revision: 1.1003 $	$Date: 1998/10/24 19:57:34 $
 *
 ***************************************************************************
 * REVISION HISTORY:
 *
 * $Log: Inform.C,v $
 * Revision 1.1003  1998/10/24 19:57:34  jim
 * Eliminated warnings generated by g++ -Wall.
 *
 * Revision 1.1002  1997/08/13 21:00:16  brunner
 * Made binary files always use 32 bits for the number of atoms, so that it
 * works on both 64 and 32-bit machines.  Also, I made Inform.C use CPrintf,
 * to fix the I/O buffering.
 *
 * Revision 1.1001  1997/03/19 11:54:20  ari
 * Add Broadcast mechanism.
 * Fixed RCS Log entries on files that did not have Log entries.
 * Added some register variables to Molecule and ComputeNonbondedExcl.C
 *
 ***************************************************************************/
