/***************************************************************************/
/*              (C) Copyright 1996 The Board of Trustees of the            */
/*                          University of Illinois                         */
/*                           All Rights Reserved                           */
/***************************************************************************/

#include "charm++.h"

#include "main.top.h"
#include "main.h"

// Needed for namd.1.X components
#include "Namd.h"
#include "Communicate.h"
#include "Inform.h"

Inform namdErr("ERROR");
Inform namdWarn("Warning");
Inform namdInfo("Info");
Inform namdDebug("** DEBUG **");

#define MIN_DEBUG_LEVEL 4
//#define DEBUGM
#include "Debug.h"

class main : public chare_object
{
public:
  main(int argc, char **argv)
  {
    // print banner
    iout << iINFO << "NAMD 2.0\n"
#if 0
         << iWARN << "          ***  UNRELEASED EXPERIMENTAL VERSION  ***\n"
#else
         << iINFO << "Please complete the registration form at\n"
         << iINFO << "http://www.ks.uiuc.edu/Research/namd/download.html\n"
         << iINFO << "and send feedback or bug reports to namd@ks.uiuc.edu\n"
#endif
         << endi;

    // Namd object is only on Pe(0)
    Namd *namd = new Namd;

    if (argc >= 2) {
	namd->startup(argv[argc-1]);
    }
    else {
       NAMD_die("main::main() no arguments, exiting\n");
    }
    DebugM(1, "main() - leaving - Charm should queue up messages now!\n");
  }
};

#include "main.bot.h"
/***************************************************************************
 * RCS INFORMATION:
 *
 *	$RCSfile: main.C,v $
 *	$Author: jim $	$Locker:  $		$State: Exp $
 *	$Revision: 1.1014 $	$Date: 1999/03/22 05:54:21 $
 *
 ***************************************************************************
 * DESCRIPTION:
 *
 ***************************************************************************
 * REVISION HISTORY:
 *
 * $Log: main.C,v $
 * Revision 1.1014  1999/03/22 05:54:21  jim
 * Changed message to release 2.0 version.
 *
 * Revision 1.1013  1999/03/08 23:02:47  jim
 * Modified startup message for experimental versions.
 *
 * Revision 1.1012  1999/02/19 04:46:05  jim
 * Changed version number to 2.0b3.
 *
 * Revision 1.1011  1998/10/24 19:58:09  jim
 * Eliminated warnings generated by g++ -Wall.
 *
 * Revision 1.1010  1998/09/15 05:18:13  jim
 * Changed web feedback address.
 *
 * Revision 1.1009  1998/09/13 21:06:17  jim
 * Cleaned up output, defaults, etc.
 *
 * Revision 1.1008  1998/05/25 21:10:35  jim
 * Started using CmiAbort().
 *
 * Revision 1.1007  1998/03/03 23:05:32  brunner
 * Changed include files for new simplified Charm++ include file structure.
 *
 * Revision 1.1006  1997/11/10 16:45:59  milind
 * Made comm a Cpv Variable.
 *
 * Revision 1.1005  1997/11/07 20:17:52  milind
 * Made NAMD to run on shared memory machines.
 *
 * Revision 1.1004  1997/10/01 16:47:04  milind
 * Removed old NAMD1 messaging and replaced it with new Message Streams library.
 *
 * Revision 1.1003  1997/03/19 11:55:03  ari
 * Add Broadcast mechanism.
 * Fixed RCS Log entries on files that did not have Log entries.
 * Added some register variables to Molecule and ComputeNonbondedExcl.C
 *
 * Revision 1.1002  1997/03/04 22:37:20  ari
 * Clean up of code.  Debug statements removal, dead code removal.
 * Minor fixes, output fixes.
 * Commented some code from the top->down.  Mainly reworked Namd, Node, main.
 *
 * Revision 1.1001  1997/02/26 16:53:21  ari
 * Cleaning and debuging for memory leaks.
 * Adding comments.
 * Removed some dead code due to use of Quiescense detection.
 *
 * Revision 1.1000  1997/02/06 15:59:35  ari
 * Resetting CVS to merge branches back into the main trunk.
 * We will stick to main trunk development as suggested by CVS manual.
 * We will set up tags to track fixed points of development/release
 * as suggested by CVS manual - all praise the CVS manual.
 *
 * Revision 1.778  1997/01/28 00:31:37  ari
 * internal release uplevel to 1.778
 *
 * Revision 1.777  1997/01/17 19:37:13  ari
 * Internal CVS leveling release.  Start development code work
 * at 1.777.1.1.
 *
 * Revision 1.11  1996/12/27 22:21:54  nealk
 * Added some debugging code.
 *
 * Revision 1.10  1996/12/11 00:04:23  milind
 * *** empty log message ***
 *
 * Revision 1.9  1996/12/10 00:13:12  ari
 * *** empty log message ***
 *
 * Revision 1.8  1996/12/06 19:54:12  ari
 * *** empty log message ***
 *
 * Revision 1.7  1996/11/22 00:18:51  ari
 * *** empty log message ***
 *
 * Revision 1.7  1996/11/07 23:08:38  ari
 * *** empty log message ***
 *
 * Revision 1.6  1996/11/05 16:59:58  ari
 * *** empty log message ***
 *
 * Revision 1.5  1996/08/16 04:39:46  ari
 * *** empty log message ***
 *
 * Revision 1.4  1996/08/16 01:54:59  ari
 * *** empty log message ***
 *
 * Revision 1.3  1996/08/15 20:32:14  brunner
 * *** empty log message ***
 *
 * Revision 1.2  1996/08/06 20:38:38  ari
 * *** empty log message ***
 *
 * Revision 1.1  1996/08/02 19:20:13  gursoy
 * Initial revision
 *
 *
 ***************************************************************************/

