/***************************************************************************/
/*         (C) Copyright 1996,1997 The Board of Trustees of the            */
/*                          University of Illinois                         */
/*                           All Rights Reserved                           */
/***************************************************************************/
/***************************************************************************
 * DESCRIPTION: Methods are primarily for pack(ing) and unpack(ing)
 * 		messages for Charm.
 *		
 ***************************************************************************/

#include "charm++.h"

#include "Migration.h"
#include "MigrateAtomsMsg.h"
#include "NamdTypes.h"
// #define DEBUGM
#define MIN_DEBUG_LEVEL 3
#include "Debug.h"

#include "PatchMgr.decl.h"
#include "PatchMap.h"
#include "HomePatch.h"
#include "packmsg.h"


MigrateAtomsMsg::MigrateAtomsMsg(PatchID src, PatchID dest, MigrationList &m) : 
      srcPatchID(src), destPatchID(dest), migrationList(m) 
{
    fromNodeID = CkMyPe();
}


PACK_MSG(MigrateAtomsMsg,
  PACK(fromNodeID);
  PACK(srcPatchID);
  PACK(destPatchID);
  PACK_RESIZE(migrationList);
)


MigrateAtomsCombinedMsg::MigrateAtomsCombinedMsg(void)
{
  fromNodeID = CkMyPe();
  totalAtoms = 0;
}

void MigrateAtomsCombinedMsg::
	add(PatchID source, PatchID destination, MigrationList &m)
{
  srcPatchID.add(source);
  destPatchID.add(destination);
  int n = m.size();
  numAtoms.add(n);
  totalAtoms += n;
  for ( int i = 0; i < n; ++i )
  {
    migrationList.add(m[i]);
  }
}


void MigrateAtomsCombinedMsg::distribute(void)
{
  int n = srcPatchID.size();
  int m = 0;
  for ( int i = 0; i < n; ++i )
  {
    MigrateAtomsMsg *msg = new MigrateAtomsMsg;
    msg->fromNodeID = fromNodeID;
    msg->srcPatchID = srcPatchID[i];
    msg->destPatchID = destPatchID[i];
    int l = numAtoms[i];
    {
      DebugM(3,"Distributing " << l << " atoms to patch " << msg->destPatchID << "\n");
      msg->migrationList.resize(l);
      for ( int j = 0; j < l; ++j ) msg->migrationList[j] = migrationList[m+j];
      m += l;
    }
    PatchMap::Object()->homePatch(msg->destPatchID)->depositMigration(msg);
  }
}


PACK_MSG(MigrateAtomsCombinedMsg,
  PACK(fromNodeID);
  PACK(totalAtoms);
  PACK_RESIZE(srcPatchID);
  PACK_RESIZE(destPatchID);
  PACK_RESIZE(numAtoms);
  PACK_RESIZE(migrationList);
)


/***************************************************************************
 * RCS INFORMATION:
 *
 *	$RCSfile: MigrateAtomsMsg.C,v $
 *	$Author: jim $	$Locker:  $		$State: Exp $
 *	$Revision: 1.10 $	$Date: 1999/09/24 17:15:09 $
 *
 * REVISION HISTORY:
 *
 * $Log: MigrateAtomsMsg.C,v $
 * Revision 1.10  1999/09/24 17:15:09  jim
 * Added packmsg.h with macros to simplify packing.
 *
 * Revision 1.9  1999/05/11 23:56:35  brunner
 * Changes for new charm version
 *
 * Revision 1.8  1998/10/24 19:57:39  jim
 * Eliminated warnings generated by g++ -Wall.
 *
 * Revision 1.7  1998/03/03 23:05:16  brunner
 * Changed include files for new simplified Charm++ include file structure.
 *
 * Revision 1.6  1997/04/11 16:54:28  jim
 * Fixed bug calling size() on possibly null pointer.
 *
 * Revision 1.5  1997/04/11 06:03:22  jim
 * Message combining implemented for atom migration.
 *
 * Revision 1.4  1997/04/10 22:29:12  jim
 * First steps towards combining atom migration messages.
 *
 * Revision 1.3  1997/03/06 22:06:04  ari
 * Removed Compute.ci
 * Comments added - more code cleaning
 *
 * Revision 1.2  1997/02/26 16:53:11  ari
 * Cleaning and debuging for memory leaks.
 * Adding comments.
 * Removed some dead code due to use of Quiescense detection.
 *
 * Revision 1.1  1997/02/17 23:47:01  ari
 * Added files for cleaning up atom migration code
 *
 ***************************************************************************/
