/***************************************************************************/
/*              (C) Copyright 1996,1997 The Board of Trustees of the       */
/*                          University of Illinois                         */
/*                           All Rights Reserved                           */
/***************************************************************************/
/***************************************************************************
 * DESCRIPTION: Namd() - launches BOC's Node, WorkDistrib, PatchMgr, ProxyMgr
 *		ReductionMgr, CollectionMgr
 *
 ***************************************************************************/

#include "unistd.h"

#include "charm++.h"

#include "main.decl.h"
#include "main.h"
#include "BOCgroup.h"
#include "Namd.h"
#include "Molecule.h"
#include "Parameters.h"
#include "SimParameters.h"
#include "ConfigList.h"
#include "Node.decl.h"
#include "Node.h"
#include "WorkDistrib.decl.h"
#include "WorkDistrib.h"
#include "PatchMgr.decl.h"
#include "PatchMgr.h"
#include "ComputeMgr.decl.h"
#include "ComputeMgr.h"
#include "ProxyMgr.decl.h"
#include "ProxyMgr.h"
#include "ReductionMgr.decl.h"
#include "ReductionMgr.h"
#include "CollectionMgr.decl.h"
#include "CollectionMgr.h"
#include "CollectionMaster.decl.h"
#include "CollectionMaster.h"
#include "BroadcastMgr.decl.h"
#include "BroadcastMgr.h"
#include "LdbCoordinator.decl.h"
#include "LdbCoordinator.h"

float Namd::cmiWallStart;
float Namd::cmiCpuStart;
int Namd::cmiFirstStart;
float Namd::cmiWallFirstStart;
float Namd::cmiCpuFirstStart;

// Namd(void ) is the constructor for the startup node.  It needs to
// read in file data,
Namd::Namd(void)
{
  BOCgroup group;

  // Create WorkDistrib and send it an empty message
  group.workDistrib = CProxy_WorkDistrib::ckNew();

  // Create ProxyMgr
  group.proxyMgr = CProxy_ProxyMgr::ckNew();

  // Create PatchMgr
  group.patchMgr = CProxy_PatchMgr::ckNew();

  // Create ComputeMgr
  group.computeMgr = CProxy_ComputeMgr::ckNew();

  // Create ReductionMgr
  group.reductionMgr = CProxy_ReductionMgr::ckNew();

  // Create Collection system
  CProxy_CollectionMaster coll(0);
  CkChareID collectionMaster = coll.ckGetChareId();
  SlaveInitMsg *initmsg7 = new SlaveInitMsg;
  initmsg7->master = collectionMaster;
  group.collectionMgr = CProxy_CollectionMgr::ckNew(initmsg7);

  // Create Broadcast system
  group.broadcastMgr = CProxy_BroadcastMgr::ckNew();

  // Create Load-balance coordinator
  group.ldbCoordinator = CProxy_LdbCoordinator::ckNew();

  // Create the Node object and send it the IDs of all the other
  // parallel objects.
  GroupInitMsg *msg = new GroupInitMsg;
  msg->group = group;

  // iout << iINFO << "Starting up nodes\n" << endi;
  nodeGroup = CProxy_Node::ckNew(msg);
}


// ~Namd(void) just needs to tell all the slave nodes to die.
Namd::~Namd(void)
{
  CkPrintf("Namd::~Namd() called\n");
}


// startup(char *) 
void Namd::startup(char *confFile)
{
  namdState.configFileInit(confFile);
  if (namdState.status()) {
    CkPrintf("Namd::startup() - could not initialize namdState from %s\n", 
      confFile);
    CkExit();
  }

  // Give our node[PE = 0] pointers to the data objects, so it can use them,
  // or send them on as messages elsewhere.
  Node::Object()->saveMolDataPointers(&namdState);

  Node::messageStartUp(); // tell all nodes to startup
}



/***************************************************************************
 * RCS INFORMATION:
 *
 *	$RCSfile: Namd.C,v $
 *	$Author: brunner $	$Locker:  $		$State: Exp $
 *	$Revision: 1.1011 $	$Date: 1999/05/11 23:56:36 $
 *
 ***************************************************************************
 * REVISION HISTORY:
 *
 * $Log: Namd.C,v $
 * Revision 1.1011  1999/05/11 23:56:36  brunner
 * Changes for new charm version
 *
 * Revision 1.1010  1998/10/24 19:57:41  jim
 * Eliminated warnings generated by g++ -Wall.
 *
 * Revision 1.1009  1998/09/13 21:06:08  jim
 * Cleaned up output, defaults, etc.
 *
 * Revision 1.1008  1998/05/22 00:33:58  jim
 * Fixed final timing when load balancing is used.
 *
 * Revision 1.1007  1998/03/03 23:05:17  brunner
 * Changed include files for new simplified Charm++ include file structure.
 *
 * Revision 1.1006  1998/02/10 23:30:29  milind
 * Fixed to reflect the current changes to Charm++ translator.
 *
 * Revision 1.1005  1997/04/04 23:34:20  milind
 * Got NAMD2 to run on Origin2000.
 * Included definitions of class static variables in C files.
 * Fixed alignment bugs by using memcpy instead of assignment in
 * pack and unpack.
 *
 * Revision 1.1004  1997/03/27 20:25:48  brunner
 * Changes for LdbCoordinator, the load balance control BOC
 *
 * Revision 1.1003  1997/03/19 11:54:34  ari
 * Add Broadcast mechanism.
 * Fixed RCS Log entries on files that did not have Log entries.
 * Added some register variables to Molecule and ComputeNonbondedExcl.C
 *
 * Revision 1.1002  1997/03/14 21:40:10  ari
 * Reorganized startup to make possible inital load
 * balancing by changing methods in WorkDistrib.
 * Also made startup more transparent and easier
 * to modify.
 *
 * Revision 1.1001  1997/03/04 22:37:10  ari
 * Clean up of code.  Debug statements removal, dead code removal.
 * Minor fixes, output fixes.
 * Commented some code from the top->down.  Mainly reworked Namd, Node, main.
 *
 * Revision 1.1000  1997/02/06 15:58:46  ari
 * Resetting CVS to merge branches back into the main trunk.
 * We will stick to main trunk development as suggested by CVS manual.
 * We will set up tags to track fixed points of development/release
 * as suggested by CVS manual - all praise the CVS manual.
 *
 * Revision 1.778  1997/01/28 00:30:55  ari
 * internal release uplevel to 1.778
 *
 * Revision 1.777  1997/01/17 19:36:30  ari
 * Internal CVS leveling release.  Start development code work
 * at 1.777.1.1.
 *
 * Revision 1.16  1997/01/13 23:26:19  jim
 * create collection system
 *
 * Revision 1.15  1997/01/09 20:48:10  jim
 * added Controller code
 *
 * Revision 1.14  1996/12/26 22:26:29  nealk
 * Added instantiation of reduction manager.
 *
 * Revision 1.13  1996/12/10 00:13:12  ari
 * *** empty log message ***
 *
 * Revision 1.12  1996/12/05 21:37:43  ari
 * *** empty log message ***
 *
 * Revision 1.11  1996/11/30 00:38:14  jim
 * added ComputeMgr creation
 *
 * Revision 1.10  1996/11/22 00:18:51  ari
 * *** empty log message ***
 *
 * Revision 1.9  1996/11/05 16:59:58  ari
 * *** empty log message ***
 *
 * Revision 1.8  1996/09/03 22:54:09  ari
 * *** empty log message ***
 *
 * Revision 1.7  1996/08/29 00:50:42  ari
 * *** empty log message ***
 *
 * Revision 1.6  1996/08/21 23:58:25  brunner
 * *** empty log message ***
 *
 * Revision 1.5  1996/08/19 22:05:31  ari
 * *** empty log message ***
 *
 * Revision 1.4  1996/08/16 21:19:34  ari
 * *** empty log message ***
 *
 * Revision 1.3  1996/08/16 20:33:09  brunner
 * Not Working
 *
 * Revision 1.2  1996/08/16 04:39:46  ari
 * *** empty log message ***
 *
 * Revision 1.1  1996/08/16 01:54:59  ari
 * Initial revision
 *
 ***************************************************************************/
